# Generated by Django 3.0.5 on 2021-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.CharField(max_length=30)),
                ('entityId', models.CharField(max_length=30)),
                ('LEI', models.BooleanField()),
                ('REPORTING_CONSENT', models.BooleanField()),
                ('AML_KYC', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('counterpartyID', models.CharField(max_length=30)),
                ('reportingCounterpartyID', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('tradeID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('reportingSide', models.CharField(max_length=30)),
                ('regulation', models.CharField(max_length=30)),
                ('jurisdiction', models.CharField(max_length=10)),
                ('securitiesFinancingTransactionType', models.CharField(max_length=20)),
            ],
        ),
    ]
