# Generated by Django 3.0.5 on 2021-07-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
