# Generated by Django 3.0.5 on 2021-07-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20210721_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isGTT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='AML_KYC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='LEI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='REPORTING_CONSENT',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
