# Generated by Django 3.0.5 on 2021-07-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20210723_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientID',
            new_name='clientId',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='entityID',
            new_name='entityId',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('clientId', 'entityId')},
        ),
    ]
