# Generated by Django 3.0.5 on 2021-07-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20210723_0719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TradeParties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterpartyID', models.CharField(max_length=30)),
                ('reportingCounterpartyID', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('counterpartyID', 'reportingCounterpartyID')},
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='clientId',
        ),
        migrations.RemoveField(
            model_name='client',
            name='entityId',
        ),
        migrations.AddField(
            model_name='client',
            name='TradingParties',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trades.TradeParties'),
            preserve_default=False,
        ),
    ]
