# Generated by Django 3.0.5 on 2021-07-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_auto_20210723_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='TradingParties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.TradeParties', unique=True),
        ),
    ]
