# Generated by Django 3.0.5 on 2021-07-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_auto_20210723_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='counterpartyID',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='reportingCounterpartyID',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
