# Generated by Django 3.0.5 on 2021-07-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_auto_20210723_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='counterpartyID',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='reportingCounterpartyID',
        ),
    ]
