# Generated by Django 3.0.5 on 2021-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_auto_20210723_1044'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['clientId', 'entityId'], name='trades_clie_clientI_fcb2db_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['regulation', 'jurisdiction', 'securitiesFinancingTransactionType', 'reportingSide'], name='trades_trad_regulat_716d3b_idx'),
        ),
    ]
