# Generated by Django 3.0.5 on 2021-07-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_auto_20210725_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowedJurisdiction', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowedRegulation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowedReportingSide', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritiesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowedSecuritiesType', models.CharField(max_length=10)),
            ],
        ),
    ]
