# Generated by Django 3.0.5 on 2021-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_jurisdiction_regulation_reportingside_securitiestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='allowedRegulation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='securitiestype',
            name='allowedSecuritiesType',
            field=models.CharField(max_length=20),
        ),
    ]
