# Generated by Django 3.0.5 on 2021-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_auto_20210726_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingCounterParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowedReportingCounterParty', models.CharField(max_length=10)),
            ],
        ),
    ]
